login/views.py
from flask import Flask, redirect, url_for, render_template, request, flash, session, jsonify, Blueprint
from flask_wtf.csrf import CSRFProtect # protector para POST request
from .modulos import validateUser
from config import *
import json

login = Blueprint('login',
				  __name__,
				  template_folder='templates',
				  static_folder='static',
				  static_url_path='/%s' % __name__)

#vista de login
@login.route('/login')
def _login():
	# borra todas las cookies al entrar
	session.clear()
	tiempoMax = Timer.SEG
	# renderiza template
	return render_template('login.html', tiempoMax=tiempoMax)
	
# método que es llamado por ajax desde template login.html
# devuelve cod_status y msg_status si es que no se puede validar
# devuelve la url del menú y crea cookie 'id_conn' si es que logra acceder

@login.route('/validar_login', methods=['POST'])
def validar_login():

	load = request.get_json()

	print('validar login')
	# se obiene el 'nombre' del load
	user = load.get('user')
	password = load.get('password')

	# se llama el servicio y se mete a un diccionario 
	respuesta = validateUser(user,password)
	print(respuesta)
	
	if respuesta.get('cod_status') == '0':
		session['id_conn'] = respuesta.get('id_conn')
		url = {'url': url_for('menu._menu') }
		info = json.dumps(url, ensure_ascii=False)
		data = {'data': info}
		return jsonify(data)

	# se transforma el diccionario en un json
	info = json.dumps(respuesta, ensure_ascii=False)

	# se define el data
	data = {'data': info}
	# se manda de vuelta
	return jsonify(data)

revision_contenido/views.py
from flask import Flask, redirect, url_for, render_template, request, flash, session, jsonify, Blueprint
import modulos as global_modulos
from config import *

revision_contenido = Blueprint('revision_contenido',
								__name__,
								template_folder='templates',
								static_folder='static',
								static_url_path='/%s' % __name__)

#vista de revisión de contenido
@revision_contenido.route('/revision_contenido/')
def _revision_contenido():
	id_conn = session.get('id_conn', None)
	if id_conn is None:
		return redirect('login')
	
	tiempoMax = Timer.SEG
	contexto = global_modulos.getInfoContexto(id_conn)
	return render_template('revision_contenido.html', contexto=contexto, tiempoMax=tiempoMax) 
	
#servicio que llama al ValidaSalida
@revision_contenido.route('/validasalida', methods=['GET'])
def valida_salida():
	id_conn = session.get('id_conn', None)
	if id_conn is None:
		return redirect('login')
	
	nro_salida = request.args.get('nro_salida', 0, type=int)
	
	cod_status, msg_status = global_modulos.ValidaSalida(id_conn, nro_salida)
	return jsonify(cod_status=cod_status, msg_status=msg_status)
	
#servicio que llama al ValidaBandeja
@revision_contenido.route('/validabandeja', methods=['GET'])
def valida_bandeja():
	id_conn = session.get('id_conn', None)
	if id_conn is None:
		return redirect('login')
	
	nro_salida = request.args.get('nro_salida', 0, type=int)
	bandeja_pub = request.args.get('bandeja_pub', 0, type=str)
	
	cod_status, msg_status = global_modulos.ValidaBandeja(id_conn, nro_salida, bandeja_pub)
	return jsonify(cod_status=cod_status, msg_status=msg_status)
	
#servicio que llama al RegistraProducto
@revision_contenido.route('/registraproducto', methods=['GET'])
def registra_producto():
	id_conn = session.get('id_conn', None)
	if id_conn is None:
		return redirect('login')
	
	nro_salida = request.args.get('nro_salida', 0, type=int)
	bandeja_pub = request.args.get('bandeja_pub', 0, type=str)
	cod_ingresado = request.args.get('cod_ingresado', 0, type=str)
	
	cantidad, descripcion, cod_status, msg_status = global_modulos.RegistraProducto(id_conn, nro_salida, bandeja_pub, cod_ingresado)
	return jsonify(cantidad=cantidad, descripcion=descripcion, cod_status=cod_status, msg_status=msg_status)
	
#servicio que llama al RevisaContenido
@revision_contenido.route('/revisacontenido', methods=['GET'])
def revisa_contenido():
	id_conn = session.get('id_conn', None)
	if id_conn is None:
		return redirect('login')
	
	nro_salida = request.args.get('nro_salida', 0, type=int)
	bandeja_pub = request.args.get('bandeja_pub', 0, type=str)
	glosa = request.args.get('glosa', 0, type=str)
	
	cod_status, msg_status = global_modulos.RevisaContenido(id_conn, nro_salida, bandeja_pub, glosa)
	return jsonify(cod_status=cod_status, msg_status=msg_status)
	
#servicio que llama al CancelaRevContenido
@revision_contenido.route('/cancelarevcontenido', methods=['GET'])
def cancelarevcontenido():
	id_conn = session.get('id_conn', None)
	if id_conn is None:
		return redirect('login')
	
	nro_salida = request.args.get('nro_salida', 0, type=int)
	bandeja_pub = request.args.get('bandeja_pub', 0, type=str)
	
	cod_status, msg_status = global_modulos.CancelaRevContenido(id_conn, nro_salida, bandeja_pub)
	return jsonify(cod_status=cod_status, msg_status=msg_status)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- Pantalla haga resize dependiendo de la resolución del dispositvo -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Ícono de la aplicación -->
    <link rel="shortcut icon" href="{{url_for('static', filename='img/faviconn.ico')}}">
    <!-- Ícono en la home screen -->
    <link rel="apple-touch-icon" sizes="128x128" href="{{ url_for('static', filename='img/desktop_icon.png')}}">
    <!-- Acceso directo no sale con la barra de url usando chrome en android-->
    <meta name="mobile-web-app-capable" content="yes">
    <!-- Título -->
    <title>{% block title %}{% endblock %} - Salcobrand</title>
    
    <!-- Bootstrap y dependencias -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    

    <!-- CSS y JS de la base: background color, img size, entre otros. -->   
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
	<script type="text/javascript" src="{{url_for('static', filename='js/base.js')}}"></script>
	<script type="text/javascript">
		var t;
		
		function ResetTimer() {
			clearTimeout(t);
			t = setTimeout(IrLogin, {{tiempoMax}});
		};
		
		function IrMenu(){
			setModalAdvertencia("Mensaje","Saliendo:","Mensaje: Usted Está Redirigiendose al Menú");
			location.href = "{{url_for('menu._menu')}}";
		};
		
		function IrLogin(){
			setModalAdvertencia("Mensaje","Saliendo:","Mensaje: Usted Está Redirigiendose al Login");
			location.href = "{{url_for('login._login')}}";
		};
	</script>
	<!-- Bloque header del hijo.
	Aquí el hijo puede agregar styles propios u otros headers que se necesiten. -->
	{% block header %}
	{% endblock %}
</head>
<!--
La pantalla se compone de un contenedor que tiene los siguientes bloques:
------------------------
|row { LOGO (base) }
|row {
|col: NOMBRE DE PANTALLA (hijo) | col: INFO CONTEXTO (hijo) |
|}
|row {
|container: conjunto de campos (hijo)
|}
|footer: {texto (base)} 
-->
<body onload="ResetTimer()" onclick="ResetTimer()" onkeypress="ResetTimer()" onscroll="ResetTimer()">
	<!-- Container base -->
	<div class="container">
		<!-- row logo -->
		<div class="row" id="logorow">
			<!-- logo lo saque de google -->  
			<img src="{{url_for('static', filename='img/logo.png')}}" id="logo">
		</div>
		<!-- row screen name | info de contexto -->
		<div class="row" id="master_row">
			<!-- screen name -->
			<div class="col-6" id='col_screen_name'>
				{% block screen_name %}
				{% endblock %}
			</div>
			<div class="col-8" id="col_contexto">
				{% block info_contexto %}
				{% endblock %}
			</div>
		</div>
		<!-- row contenedor de campos -->
		<div class="row">
			<div class="container h-100">
				<!-- div del gif con el loader, parte hidden -->
				<div id="loader" style="display: none;">
					<center><img src="{{url_for('static',filename='img/ajax-loader.gif')}}"></center>
				</div>
				
				<!-- Modal -->
				<div class="modal fade" id="modalAdvertencia" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
					<div class="modal-dialog modal-dialog-centered" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="modalAdvertenciaTitle">TITULO</h5>
								<!--<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>-->
							</div>
							<div class="modal-body">
								<div class="col-12">
									<div class="icoModal"><img src="{{url_for('static', filename='modal/iconos/Error.png')}}" id="modalAdvertenciaIcono"></div>
									<div class="menModal" id="modalAdvertenciaMensaje">MENSAJE</div>
								</div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-info" onclick="cerrarModal()">Cerrar</button>
								<!--<button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>-->
							</div>
						</div>
					</div>
				</div>
				{% block field_container %}
				{% endblock %}
			</div>
		</div>
	</div>
	
    <!--    JQUERY    -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- Pantalla haga resize dependiendo de la resolución del dispositvo -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Ícono de la aplicación -->
    <link rel="shortcut icon" href="{{url_for('static', filename='img/faviconn.ico')}}">
    <!-- Ícono en la home screen -->
    <link rel="apple-touch-icon" sizes="128x128" href="{{ url_for('static', filename='img/desktop_icon.png')}}">
    <!-- Acceso directo no sale con la barra de url usando chrome en android-->
    <meta name="mobile-web-app-capable" content="yes">
    <!-- Título -->
    <title>{% block title %}{% endblock %} - Salcobrand</title>
    
    <!-- Bootstrap y dependencias -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

    <!-- CSS de la base: background color, img size, entre otros. -->   
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
	<script type="text/javascript" src="{{url_for('static', filename='js/base.js')}}"></script>
	<script type="text/javascript">
		var t;
		
		function ResetTimer() {
			clearTimeout(t);
			t = setTimeout(IrLogin, {{tiempoMax}});
		};
		
		function IrMenu(){
			setModalAdvertencia("Mensaje","Saliendo:","Mensaje: Usted Está Redirigiendose al Menú");
			location.href = "{{url_for('menu._menu')}}";
		};
		
		function IrLogin(){
			setModalAdvertencia("Mensaje","Saliendo:","Mensaje: Usted Está Redirigiendose al Login");
			location.href = "{{url_for('login._login')}}";
		};
	</script>
    <!-- Bloque header del hijo.
    Aquí el hijo puede agregar styles propios u otros headers que se necesiten. -->
    {% block header %}
    {% endblock %}
</head>
<body onload="ResetTimer()" onclick="ResetTimer()" onkeypress="ResetTimer()" onscroll="ResetTimer()">
	{% block body %}
	{% endblock %}
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block title %}
	Login
{% endblock %}

{% block screen_name %}
<h2 style="color: #1a8dff;">Login</h2>
{% endblock %}

{% block header %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

	<script type="text/javascript">
		$(function(){

			$("#loginInput").focus();

			$("#loginInput").keypress(function(event) {
				// detecta además del keycode de un teclado físico, el keycode del teclado de android
				var keycode = (event.keyCode ? event.keyCode : event.which);
				 
				// si es 'enter' y el largo es > 0
				if (keycode == 13 && $(this).val().length > 0) {
					$("#passwordInput").focus();
				}
			});

			$("#passwordInput").keypress(function(event){

				// detecta además del keycode de un teclado físico, el keycode del teclado de android
				var keycode = (event.keyCode ? event.keyCode : event.which);
				 
				// si es 'enter' y el largo es > 0
				if (keycode == 13 && $(this).val().length > 0) {
					validarLogin();
				}
			});

			$("#ingresarId").bind('click', function(event){
				validarLogin();
			});
		});
		function validarLogin(){
			user = $("#loginInput").val();
			password = $("#passwordInput").val();
			/* TOKEN DE SEGURIDAD */
			var csrf_token = "{{ csrf_token() }}";
		    $.ajaxSetup({
		        beforeSend: function(xhr, settings) {
		            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
		                xhr.setRequestHeader("X-CSRFToken", csrf_token);
		            }
		        }
		    });
		    /* Llamado a ajax */
			$.ajax({
				data: JSON.stringify({ 
							'user' : user, 
							'password': password
						}),
				type: 'POST',
				url: "{{ url_for('validar_login') }}",
				contentType: 'application/json',
			    success: function(result) {
					console.log(result['data']);
					var obj = $.parseJSON(result['data']);
					console.log(obj['cod_status']);
					/*
					Si el mensaje es 1 (error):
					se muestra alerta con el mensaje
					se dejan los campos de login y password en blanco
					se pone el focus en el usuario	
					*/
					if(obj['cod_status'] == 1){
						alert(obj['msg_status']);
						$("#loginInput").val('');
						$("#passwordInput").val('');
						$("#loginInput").focus();
					}
					else{
						$.ajax({
							data: JSON.stringify({
										'id_conn': obj['id_conn']
									}),
							type: 'POST',
							url: "{{ url_for('set_info_contexto') }}",
							contentType: 'application/json',
							success: function(result){
								window.location = result;
							}
						});
						// Llamar servicio para ingreso de login
					}
			    },
			    error: function(XMLHttpRequest, textStatus, errorThrown) { 
			        alert("Status: " + textStatus);
			        alert("Error: " + errorThrown);
			    }       
			});
			return this;
		};
	</script>
	<style type="text/css">
		#fieldscol{
		    padding: 10px 10px 10px;
		    background-color: #1a8dff;
		    color: white;
		}
	</style>
{% endblock %}

{% block field_container %}
<div class="d-flex align-items-center justify-content-center h-100">
    <div class="col" id="fieldscol">
		<meta name="csrf-token" content="{{ csrf_token() }}">
	    <div class="form-group">
	        <label for="logInput">Usuario:</label>
	        <input type="text" class="form-control" id="loginInput" required autofocus>
	    </div>
	    <div class="form-group">
            <label for="passInput">Contraseña:</label>
            <input type="password" class="form-control" id="passwordInput" required>
        </div>
	    <div class="d-flex align-items-center justify-content-center">
	        <button class="btn btn-default align-self-center p-2" type="" id="ingresarId">Ingresar</button>
        </div>
    </div>
</div>
{% endblock %}

templates/revision_contenido.html
{% extends 'base.html' %}


{% block title %}
    Revisión Conenido
{% endblock %}

{% block header %}
<style type="text/css">
    .col-9{
    text-align: right;
}
#col_contexto{
    border: black 2px;
}

/* agrega una pequeña distancia entre filas de label-input */
#colx .row{
    text-align: left;
    margin-bottom: 10px;
    align-items: left;
}
/* crea un margen y el color de fondo col que contiene los campos */
#fieldscol{
    padding: 10px 10px 10px;
    background-color: #1a8dff;
    color: white;
}

/* crea un margen en el row base que contiene todo */
#baserow{
    padding: 10px 10px 10px;
}

/* para alinear los label con sus inputs */
input #form-control{
    margin-top: 5px;
    margin-bottom: 5px;
    display:inline-block;
    vertical-align:middle;
    margin-left:20px
}

label {
    display:inline-block;
    float: left;
    padding-top: 5px;
    text-align: left;
    width: 140px;
}
</style>
{% endblock %}

{% block screen_name %}
    <h4 style="color: #1a8dff;">Revisión de Contenido</h4>
{% endblock %}

{% block info_contexto %}
<!-- info de contexto -->
    {% for key,value in contexto.items() %}
    <div class="row">
        <div class="col-3">{{key}}:</div>
        <div class="col-9">{{value}}</div>
    </div>
    {% endfor %}
{% endblock %}

{% block field_container %}
<!-- contenedor de campos -->
    <div class="row" id="baserow">
        <div class="col" id="fieldscol">
            <div class="d-flex align-items-center justify-content-center h-100">
                <div class="col" id="colx">
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-5">
                            <label>Salida:</label>
                        </div>
                        <div class="col">
                            <input type="number" class="form-control" id="salidaInput" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-5">
                            <label>Bandeja:</label>
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" id="bandejaInput" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-5">
                            <label>Producto:</label>
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" id="productoInput" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-5">
                            <label>Cantidad:</label>
                        </div>
                        <div class="col">
                            <input type="number" class="form-control" id="cantidadInput" readonly="">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="text" class="form-control" id="nomberInput" placeholder="Aspirina" readonly="">
                        </div>
                    </div>
                </div>
            </div><!-- flex align-items-center -->
        </div><!-- col -->
    </div><!-- baserow -->    
    <div class="row" style="margin-top: 10px;">
        <div class="col">
            <div class="center-block text-center">
                <button type="submit" class="btn btn-info" style="float: right;">Terminar</button>
            </div>
        </div>
    </div>
{% endblock %}